#---------------------------------------------------------------------------------------------------------------------------
#exec
#---------------------------------------------------------------------------------------------------------------------------
#
exec-once=aetherlock
exec-once=xdg-user-dirs-update
#exec=killall nyroshell 2>/dev/null || true && nyroshell & disown
#exec=killall panel 2>/dev/null || true && panel & disown
#exec=killall desktop 2>/dev/null || true && desktop & disown
#exec=killall AetherDock 2>/dev/null || true && AetherDock & disown
exec-once=panel
exec-once=desktop
exec-once=AetherDock
exec-once=~/.config/aether/autostart.sh
exec-once=run-wlsunset.sh init
exec-once=init-screen-scale
exec-once=init-lockscreen
exec-once=udiskie --automount --notify
exec-once=nm-applet
exec-once=osd-notify
exec-once=auth
exec-once=aetheridle before-sleep aetherlock
exec-once=aether_clipboard
