[Idle]
DimTimeoutBattery=120
DimTimeoutAC=300
BlankTimeoutBattery=300
BlankTimeoutAC=600
SuspendTimeoutBattery=900
SuspendTimeoutAC=0

[Battery]
LowLevel=10
CriticalLevel=5
DangerLevel=2

[Actions]
LidActionBattery=suspend
LidActionAC=nothing
PowerButtonAction=interactive
